import { ConfirmRegistry, type ConfirmRegistryOptions } from "./confirm-registry.ts";
import type { InlineKeyboardButton } from "./telegram.ts";

export type FleetConfirmKind = "kill" | "rm" | "rm-topic";

export interface PendingFleetConfirm {
  id: string;
  kind: FleetConfirmKind;
  /** Empty for `rm-topic` - that variant acts on `topicId` directly, there is no session row (by
   * definition: it's an orphaned topic with nothing in the DB to look up). */
  slugs: string[];
  topicId: number | undefined;
  messageId: number;
  createdAt: number;
}

const DEFAULT_TTL_MS = 5 * 60 * 1000;

/** TTL + clock injection, both from `ConfirmRegistry` - this registry adds nothing of its own. */
export type FleetConfirmRegistryOptions = ConfirmRegistryOptions;

/**
 * Confirmation registry for `/kill --all`, `/rm --all` (§4.2), and `rm-topic` (§4.5.2 - a bare
 * `/rm` sent inside a Telegram topic that has no matching session row, i.e. an orphaned topic left
 * behind by an earlier `deleteForumTopic` failure) - all three act on something irreversible in one
 * shot, so unlike every other fleet command they go through the same approve/deny-button pattern as
 * a permission prompt (§6.3, permission-registry.ts) instead of executing immediately. A much
 * shorter TTL than the 30-minute permission-prompt one: this is an operator confirming their own
 * just-typed command, not waiting on Claude, so a stale button they forgot about should go cold
 * fast rather than stay armed to fire a fleet-wide kill/remove (or a topic delete) on a late,
 * half-remembered tap.
 */
export class FleetConfirmRegistry extends ConfirmRegistry<PendingFleetConfirm> {
  constructor(opts: FleetConfirmRegistryOptions = {}) {
    super(DEFAULT_TTL_MS, opts);
  }
}

export interface FleetConfirmCallback {
  id: string;
  kind: FleetConfirmKind;
  confirmed: boolean;
}

/**
 * `fc:<kill|rm|rm-topic>:<id>:<y|n>` - a fresh namespace alongside `perm:`/`ask:`/`run:`, well
 * inside Telegram's 64-byte `callback_data` cap. The id is generated by the Bridge itself (no
 * channel round-trip involved here, unlike a permission request's `request_id`). Re-validates the
 * format rather than trusting the tap - same defensive pattern as resolvePermCallback/
 * resolveAskCallback/resolveCommandAction: any client that can see the message can send arbitrary
 * `callback_data`.
 */
export function resolveFleetConfirmCallback(data: string): FleetConfirmCallback | null {
  const match = data.match(/^fc:(kill|rm|rm-topic):([A-Za-z0-9]{1,20}):(y|n)$/);
  if (!match) return null;
  const kind = match[1] as FleetConfirmKind;
  const id = match[2] ?? "";
  const confirmed = match[3] === "y";
  return { id, kind, confirmed };
}

export function buildFleetConfirmKeyboard(kind: FleetConfirmKind, id: string): InlineKeyboardButton[][] {
  return [
    [
      { text: "✅ Yes, proceed", callback_data: `fc:${kind}:${id}:y` },
      { text: "⛔ Cancel", callback_data: `fc:${kind}:${id}:n` },
    ],
  ];
}
