import type { InlineKeyboardButton } from "./telegram.ts";

export type FleetConfirmKind = "kill" | "rm";

export interface PendingFleetConfirm {
  id: string;
  kind: FleetConfirmKind;
  slugs: string[];
  topicId: number;
  messageId: number;
  createdAt: number;
}

const DEFAULT_TTL_MS = 5 * 60 * 1000;

export interface FleetConfirmRegistryOptions {
  ttlMs?: number;
  /** Clock injection for expiry tests - never `Date.now()` directly in the class body. */
  now?: () => number;
}

/**
 * Confirmation registry for `/kill --all` and `/rm --all` (§4.2) - both act on the whole fleet in
 * one shot, so unlike every other fleet command they go through the same approve/deny-button
 * pattern as a permission prompt (§6.3, permission-registry.ts) instead of executing immediately.
 * A much shorter TTL than the 30-minute permission-prompt one: this is an operator confirming their
 * own just-typed command, not waiting on Claude, so a stale button they forgot about should go cold
 * fast rather than stay armed to fire a fleet-wide kill/remove on a late, half-remembered tap.
 */
export class FleetConfirmRegistry {
  private readonly pending = new Map<string, PendingFleetConfirm>();
  private readonly ttlMs: number;
  private readonly now: () => number;

  constructor(opts: FleetConfirmRegistryOptions = {}) {
    this.ttlMs = opts.ttlMs ?? DEFAULT_TTL_MS;
    this.now = opts.now ?? Date.now;
  }

  add(entry: Omit<PendingFleetConfirm, "createdAt">): void {
    this.pending.set(entry.id, { ...entry, createdAt: this.now() });
  }

  /** An unknown or expired id is a no-op, not a crash - a stale/duplicate tap is expected, same as
   * resolvePermCallback's handling in permission-registry.ts. */
  resolve(id: string): PendingFleetConfirm | undefined {
    const entry = this.pending.get(id);
    if (!entry) return undefined;
    this.pending.delete(id);
    if (this.now() - entry.createdAt > this.ttlMs) return undefined;
    return entry;
  }
}

export interface FleetConfirmCallback {
  id: string;
  kind: FleetConfirmKind;
  confirmed: boolean;
}

/**
 * `fc:<kill|rm>:<id>:<y|n>` - a fresh namespace alongside `perm:`/`ask:`/`run:`, well inside
 * Telegram's 64-byte `callback_data` cap. The id is generated by the Bridge itself (no channel
 * round-trip involved here, unlike a permission request's `request_id`). Re-validates the format
 * rather than trusting the tap - same defensive pattern as resolvePermCallback/resolveAskCallback/
 * resolveCommandAction: any client that can see the message can send arbitrary `callback_data`.
 */
export function resolveFleetConfirmCallback(data: string): FleetConfirmCallback | null {
  const match = data.match(/^fc:(kill|rm):([A-Za-z0-9]{1,20}):(y|n)$/);
  if (!match) return null;
  const kind = match[1] as FleetConfirmKind;
  const id = match[2] ?? "";
  const confirmed = match[3] === "y";
  return { id, kind, confirmed };
}

export function buildFleetConfirmKeyboard(kind: FleetConfirmKind, id: string): InlineKeyboardButton[][] {
  return [
    [
      { text: "✅ Yes, proceed", callback_data: `fc:${kind}:${id}:y` },
      { text: "⛔ Cancel", callback_data: `fc:${kind}:${id}:n` },
    ],
  ];
}
